import React from 'react'

const Login = () => {
  return (
    
<div>
  <div className="login-container">
    <div className="login-login">
      <div className="login-bg" />
      <span className="login-text">
        <span>LOGO</span>
      </span>
      <span className="login-text02">
        <span>Myot</span>
      </span>
      <span className="login-text04">
        <span>Please fill your detail to access your account.</span>
      </span>
      <div className="login-button">
        <div className="login-bg1">
          <img
            alt="Rectangle122189"
            src="/rectangle122189-2uws.svg"
            className="login-rectangle12"
          />
        </div>
        <div className="login-text06">
          <span className="login-text07">
            <span>Log in</span>
          </span>
        </div>
      </div>
      <div className="login-reset-password">
        <span className="login-text09">
          <span>Reset Password?</span>
        </span>
      </div>
      <div className="login-remember">
        <div className="login-checkbox" />
        <div className="login-rememberme">
          <span className="login-text11">
            <span>Remember me</span>
          </span>
        </div>
      </div>
      <div className="login-bg2">
        <img alt="bg2190" src="/bg2190-6sy.svg" className="login-bg3" />
      </div>
      <div className="login-hide">
        <img alt="Hide2190" src="/hide2190-y2na.svg" className="login-hide1" />
      </div>
      <div className="login-dot">
        <img
          alt="Ellipse132191"
          src="/ellipse132191-hfui-200h.png"
          className="login-ellipse13"
        />
        <img
          alt="Ellipse142191"
          src="/ellipse142191-clf4-200h.png"
          className="login-ellipse14"
        />
        <img
          alt="Ellipse152191"
          src="/ellipse152191-fdda-200h.png"
          className="login-ellipse15"
        />
        <img
          alt="Ellipse162191"
          src="/ellipse162191-o6v-200h.png"
          className="login-ellipse16"
        />
        <img
          alt="Ellipse172191"
          src="/ellipse172191-0gal-200h.png"
          className="login-ellipse17"
        />
        <img
          alt="Ellipse182191"
          src="/ellipse182191-vodn-200h.png"
          className="login-ellipse18"
        />
        <img
          alt="Ellipse192191"
          src="/ellipse192191-y56f-200h.png"
          className="login-ellipse19"
        />
        <img
          alt="Ellipse202191"
          src="/ellipse202191-p7os-200h.png"
          className="login-ellipse20"
        />
      </div>
      <div className="login-pawssword">
        <span className="login-text13">
          <span>Password</span>
        </span>
      </div>
      <div className="login-bg4">
        <img alt="bg2192" src="/bg2192-1b5k.svg" className="login-bg5" />
      </div>
      <div className="login-email">
        <span className="login-text15">
          <span>example@gmail.com</span>
        </span>
      </div>
      <div className="login-emailaddress">
        <span className="login-text17">
          <span>Email Address</span>
        </span>
      </div>
      <div className="login-container1">
        <div className="login-group427322825">
          <img
            alt="Vector2192"
            src="/vector2192-5gem.svg"
            className="login-vector"
          />
          <img
            alt="Vector2193"
            src="/vector2193-a1mf.svg"
            className="login-vector001"
          />
          <img
            alt="Vector2193"
            src="/vector2193-a4ye.svg"
            className="login-vector002"
          />
          <img
            alt="Vector2193"
            src="/vector2193-eab4.svg"
            className="login-vector003"
          />
          <img
            alt="Vector2193"
            src="/vector2193-3uc.svg"
            className="login-vector004"
          />
          <img
            alt="Vector2193"
            src="/vector2193-jgxp.svg"
            className="login-vector005"
          />
          <img
            alt="Vector2193"
            src="/vector2193-8um.svg"
            className="login-vector006"
          />
          <img
            alt="Vector2193"
            src="/vector2193-fzdm.svg"
            className="login-vector007"
          />
          <img
            alt="Vector2193"
            src="/vector2193-7m2h.svg"
            className="login-vector008"
          />
          <img
            alt="Vector2193"
            src="/vector2193-rxi.svg"
            className="login-vector009"
          />
          <img
            alt="Vector2193"
            src="/vector2193-svxl.svg"
            className="login-vector010"
          />
          <img
            alt="Vector2194"
            src="/vector2194-m9kb.svg"
            className="login-vector011"
          />
          <img
            alt="Vector2194"
            src="/vector2194-n9b.svg"
            className="login-vector012"
          />
          <img
            alt="Vector2194"
            src="/vector2194-yybk.svg"
            className="login-vector013"
          />
          <img
            alt="Vector2194"
            src="/vector2194-mkgh.svg"
            className="login-vector014"
          />
          <img
            alt="Vector2194"
            src="/vector2194-vz8k.svg"
            className="login-vector015"
          />
          <img
            alt="Vector2194"
            src="/vector2194-5fci.svg"
            className="login-vector016"
          />
          <img
            alt="Vector2194"
            src="/vector2194-g8zc.svg"
            className="login-vector017"
          />
          <img
            alt="Vector2194"
            src="/vector2194-djsn.svg"
            className="login-vector018"
          />
          <img
            alt="Vector2194"
            src="/vector2194-1xlu.svg"
            className="login-vector019"
          />
          <img
            alt="Vector2194"
            src="/vector2194-eroe.svg"
            className="login-vector020"
          />
          <img
            alt="Vector2195"
            src="/vector2195-68rq.svg"
            className="login-vector021"
          />
          <img
            alt="Vector2195"
            src="/vector2195-1w6o.svg"
            className="login-vector022"
          />
          <img
            alt="Vector2195"
            src="/vector2195-f6pj.svg"
            className="login-vector023"
          />
          <img
            alt="Vector2195"
            src="/vector2195-a9go.svg"
            className="login-vector024"
          />
          <img
            alt="Vector2195"
            src="/vector2195-t4ut.svg"
            className="login-vector025"
          />
          <img
            alt="Vector2195"
            src="/vector2195-ygkr.svg"
            className="login-vector026"
          />
          <img
            alt="Vector2195"
            src="/vector2195-1bla.svg"
            className="login-vector027"
          />
          <img
            alt="Vector2195"
            src="/vector2195-nfni.svg"
            className="login-vector028"
          />
          <img
            alt="Vector2195"
            src="/vector2195-td8.svg"
            className="login-vector029"
          />
          <img
            alt="Vector2195"
            src="/vector2195-1wc.svg"
            className="login-vector030"
          />
          <img
            alt="Vector2196"
            src="/vector2196-7r8.svg"
            className="login-vector031"
          />
          <img
            alt="Vector2196"
            src="/vector2196-nprrh.svg"
            className="login-vector032"
          />
          <img
            alt="Vector2196"
            src="/vector2196-hzop.svg"
            className="login-vector033"
          />
          <img
            alt="Vector2196"
            src="/vector2196-1k8n.svg"
            className="login-vector034"
          />
          <img
            alt="Vector2196"
            src="/vector2196-6mj.svg"
            className="login-vector035"
          />
          <img
            alt="Vector2196"
            src="/vector2196-z6ri.svg"
            className="login-vector036"
          />
          <img
            alt="Vector2196"
            src="/vector2196-r7uxe.svg"
            className="login-vector037"
          />
          <img
            alt="Vector2196"
            src="/vector2196-uieb.svg"
            className="login-vector038"
          />
          <img
            alt="Vector2196"
            src="/vector2196-ugk5.svg"
            className="login-vector039"
          />
          <img
            alt="Vector2196"
            src="/vector2196-oqxt.svg"
            className="login-vector040"
          />
          <img
            alt="Vector2197"
            src="/vector2197-5xz8.svg"
            className="login-vector041"
          />
          <img
            alt="Vector2197"
            src="/vector2197-txan.svg"
            className="login-vector042"
          />
          <img
            alt="Vector2197"
            src="/vector2197-6bfo.svg"
            className="login-vector043"
          />
          <img
            alt="Vector2197"
            src="/vector2197-0hij.svg"
            className="login-vector044"
          />
          <img
            alt="Vector2197"
            src="/vector2197-pf6q.svg"
            className="login-vector045"
          />
          <img
            alt="Vector2197"
            src="/vector2197-ngkn.svg"
            className="login-vector046"
          />
          <img
            alt="Vector2197"
            src="/vector2197-ezia.svg"
            className="login-vector047"
          />
          <img
            alt="Vector2197"
            src="/vector2197-vkpg.svg"
            className="login-vector048"
          />
          <img
            alt="Vector2197"
            src="/vector2197-oy2q.svg"
            className="login-vector049"
          />
          <img
            alt="Vector2197"
            src="/vector2197-5pbs.svg"
            className="login-vector050"
          />
          <img
            alt="Vector2198"
            src="/vector2198-8f7f.svg"
            className="login-vector051"
          />
          <img
            alt="Vector2198"
            src="/vector2198-thha.svg"
            className="login-vector052"
          />
          <img
            alt="Vector2198"
            src="/vector2198-iegx.svg"
            className="login-vector053"
          />
          <img
            alt="Vector2198"
            src="/vector2198-1oqj.svg"
            className="login-vector054"
          />
          <img
            alt="Vector2198"
            src="/vector2198-qo64.svg"
            className="login-vector055"
          />
          <img
            alt="Vector2198"
            src="/vector2198-5mtz.svg"
            className="login-vector056"
          />
          <img
            alt="Vector2198"
            src="/vector2198-qjij.svg"
            className="login-vector057"
          />
          <img
            alt="Vector2198"
            src="/vector2198-1es.svg"
            className="login-vector058"
          />
          <img
            alt="Vector2198"
            src="/vector2198-xaq.svg"
            className="login-vector059"
          />
          <img
            alt="Vector2198"
            src="/vector2198-9de9.svg"
            className="login-vector060"
          />
          <img
            alt="Vector2199"
            src="/vector2199-wa7o.svg"
            className="login-vector061"
          />
          <img
            alt="Vector2199"
            src="/vector2199-asac.svg"
            className="login-vector062"
          />
          <img
            alt="Vector2199"
            src="/vector2199-29g.svg"
            className="login-vector063"
          />
          <img
            alt="Vector2199"
            src="/vector2199-u88.svg"
            className="login-vector064"
          />
          <img
            alt="Vector2199"
            src="/vector2199-ztxq.svg"
            className="login-vector065"
          />
          <img
            alt="Vector2199"
            src="/vector2199-86dq.svg"
            className="login-vector066"
          />
          <img
            alt="Vector2199"
            src="/vector2199-f3el.svg"
            className="login-vector067"
          />
          <img
            alt="Vector2199"
            src="/vector2199-qnkj.svg"
            className="login-vector068"
          />
          <img
            alt="Vector2199"
            src="/vector2199-wthm.svg"
            className="login-vector069"
          />
          <img
            alt="Vector2199"
            src="/vector2199-4lnt.svg"
            className="login-vector070"
          />
          <img
            alt="Vector2200"
            src="/vector2200-npqh.svg"
            className="login-vector071"
          />
          <img
            alt="Vector2200"
            src="/vector2200-muqe.svg"
            className="login-vector072"
          />
          <img
            alt="Vector2200"
            src="/vector2200-yjs.svg"
            className="login-vector073"
          />
          <img
            alt="Vector2200"
            src="/vector2200-e66i.svg"
            className="login-vector074"
          />
          <img
            alt="Vector2200"
            src="/vector2200-bx34.svg"
            className="login-vector075"
          />
          <img
            alt="Vector2200"
            src="/vector2200-jozc.svg"
            className="login-vector076"
          />
          <img
            alt="Vector2200"
            src="/vector2200-7kdt.svg"
            className="login-vector077"
          />
          <img
            alt="Vector2200"
            src="/vector2200-wd2.svg"
            className="login-vector078"
          />
          <img
            alt="Vector2200"
            src="/vector2200-hs1l.svg"
            className="login-vector079"
          />
          <img
            alt="Vector2200"
            src="/vector2200-7pmu.svg"
            className="login-vector080"
          />
          <img
            alt="Vector2201"
            src="/vector2201-lwrq.svg"
            className="login-vector081"
          />
          <img
            alt="Vector2201"
            src="/vector2201-2lpi.svg"
            className="login-vector082"
          />
          <img
            alt="Vector2201"
            src="/vector2201-ti9cg.svg"
            className="login-vector083"
          />
          <img
            alt="Vector2201"
            src="/vector2201-fysl.svg"
            className="login-vector084"
          />
          <img
            alt="Vector2201"
            src="/vector2201-jz5.svg"
            className="login-vector085"
          />
          <img
            alt="Vector2201"
            src="/vector2201-hbsn.svg"
            className="login-vector086"
          />
          <img
            alt="Vector2201"
            src="/vector2201-q4v.svg"
            className="login-vector087"
          />
          <img
            alt="Vector2201"
            src="/vector2201-1hpg.svg"
            className="login-vector088"
          />
          <img
            alt="Vector2201"
            src="/vector2201-2lvc.svg"
            className="login-vector089"
          />
          <img
            alt="Vector2201"
            src="/vector2201-38f.svg"
            className="login-vector090"
          />
          <img
            alt="Vector2202"
            src="/vector2202-78qr.svg"
            className="login-vector091"
          />
          <img
            alt="Vector2202"
            src="/vector2202-yjml.svg"
            className="login-vector092"
          />
          <img
            alt="Vector2202"
            src="/vector2202-iduj.svg"
            className="login-vector093"
          />
          <img
            alt="Vector2202"
            src="/vector2202-11sw.svg"
            className="login-vector094"
          />
          <img
            alt="Vector2202"
            src="/vector2202-k1n.svg"
            className="login-vector095"
          />
          <img
            alt="Vector2202"
            src="/vector2202-l26s.svg"
            className="login-vector096"
          />
          <img
            alt="Vector2202"
            src="/vector2202-p35k.svg"
            className="login-vector097"
          />
          <img
            alt="Vector2202"
            src="/vector2202-75ya.svg"
            className="login-vector098"
          />
          <img
            alt="Vector2202"
            src="/vector2202-xjqd.svg"
            className="login-vector099"
          />
          <img
            alt="Vector2202"
            src="/vector2202-abft.svg"
            className="login-vector100"
          />
          <img
            alt="Vector2203"
            src="/vector2203-8ft3.svg"
            className="login-vector101"
          />
          <img
            alt="Vector2203"
            src="/vector2203-jpya.svg"
            className="login-vector102"
          />
          <img
            alt="Vector2203"
            src="/vector2203-sf7.svg"
            className="login-vector103"
          />
          <img
            alt="Vector2203"
            src="/vector2203-0jh.svg"
            className="login-vector104"
          />
          <img
            alt="Vector2203"
            src="/vector2203-361r.svg"
            className="login-vector105"
          />
          <img
            alt="Vector2203"
            src="/vector2203-wzn8.svg"
            className="login-vector106"
          />
          <img
            alt="Vector2203"
            src="/vector2203-buif.svg"
            className="login-vector107"
          />
          <img
            alt="Vector2203"
            src="/vector2203-8xhj.svg"
            className="login-vector108"
          />
          <img
            alt="Vector2203"
            src="/vector2203-1zm7.svg"
            className="login-vector109"
          />
          <img
            alt="Vector2203"
            src="/vector2203-5tj.svg"
            className="login-vector110"
          />
          <img
            alt="Vector2204"
            src="/vector2204-rx6j.svg"
            className="login-vector111"
          />
          <img
            alt="Vector2204"
            src="/vector2204-qhv.svg"
            className="login-vector112"
          />
          <img
            alt="Vector2204"
            src="/vector2204-npt.svg"
            className="login-vector113"
          />
          <img
            alt="Vector2204"
            src="/vector2204-bg0x.svg"
            className="login-vector114"
          />
          <img
            alt="Vector2204"
            src="/vector2204-b5e6.svg"
            className="login-vector115"
          />
          <img
            alt="Vector2204"
            src="/vector2204-io5.svg"
            className="login-vector116"
          />
          <img
            alt="Vector2204"
            src="/vector2204-gky.svg"
            className="login-vector117"
          />
          <img
            alt="Vector2204"
            src="/vector2204-vmg.svg"
            className="login-vector118"
          />
          <img
            alt="Vector2204"
            src="/vector2204-da46.svg"
            className="login-vector119"
          />
          <img
            alt="Vector2204"
            src="/vector2204-6obn.svg"
            className="login-vector120"
          />
          <img
            alt="Vector2205"
            src="/vector2205-6uc8.svg"
            className="login-vector121"
          />
          <img
            alt="Vector2205"
            src="/vector2205-w1ed.svg"
            className="login-vector122"
          />
          <img
            alt="Vector2205"
            src="/vector2205-4ru.svg"
            className="login-vector123"
          />
          <img
            alt="Vector2205"
            src="/vector2205-n2cz.svg"
            className="login-vector124"
          />
          <img
            alt="Vector2205"
            src="/vector2205-ob.svg"
            className="login-vector125"
          />
          <img
            alt="Vector2205"
            src="/vector2205-sonc.svg"
            className="login-vector126"
          />
          <img
            alt="Vector2205"
            src="/vector2205-mpz4.svg"
            className="login-vector127"
          />
          <img
            alt="Vector2205"
            src="/vector2205-t0af.svg"
            className="login-vector128"
          />
          <img
            alt="Vector2205"
            src="/vector2205-ku4f.svg"
            className="login-vector129"
          />
          <img
            alt="Vector2205"
            src="/vector2205-lozb.svg"
            className="login-vector130"
          />
          <img
            alt="Vector2206"
            src="/vector2206-719p.svg"
            className="login-vector131"
          />
        </div>
      </div>
    </div>
  </div>
</div>

)
}

export default Login;